// 使用常量替代 Mutation 事件类型
export const RECORD_USERINFO = 'RECORD_USERINFO'
export const OUT_LOGIN = 'OUT_LOGIN'
export const GET_USERINFO = 'GET_USERINFO'
export const GET_SCORE = 'GET_SCORE'
export const GET_USERID = 'GET_USERID'
export const SET_CART = 'SET_CART'
export const GET_CART = 'GET_CART'
export const REDUCE_CART = 'REDUCE_CART'
export const REMOVE_CART = 'REMOVE_CART'
